# CMake generated Testfile for 
# Source directory: C:/git/library/abseil/abseil-cpp/absl/random
# Build directory: C:/git/library/abseil/abseil-cpp/absl/random
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_bit_gen_ref_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_bit_gen_ref_test.exe")
  set_tests_properties(absl_random_bit_gen_ref_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;51;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_bit_gen_ref_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_bit_gen_ref_test.exe")
  set_tests_properties(absl_random_bit_gen_ref_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;51;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_bit_gen_ref_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_bit_gen_ref_test.exe")
  set_tests_properties(absl_random_bit_gen_ref_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;51;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_bit_gen_ref_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_bit_gen_ref_test.exe")
  set_tests_properties(absl_random_bit_gen_ref_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;51;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_bit_gen_ref_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_mock_distributions_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_mock_distributions_test.exe")
  set_tests_properties(absl_random_mock_distributions_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;128;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_mock_distributions_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_mock_distributions_test.exe")
  set_tests_properties(absl_random_mock_distributions_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;128;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_mock_distributions_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_mock_distributions_test.exe")
  set_tests_properties(absl_random_mock_distributions_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;128;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_mock_distributions_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_mock_distributions_test.exe")
  set_tests_properties(absl_random_mock_distributions_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;128;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_mock_distributions_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_mocking_bit_gen_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_mocking_bit_gen_test.exe")
  set_tests_properties(absl_random_mocking_bit_gen_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;144;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_mocking_bit_gen_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_mocking_bit_gen_test.exe")
  set_tests_properties(absl_random_mocking_bit_gen_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;144;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_mocking_bit_gen_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_mocking_bit_gen_test.exe")
  set_tests_properties(absl_random_mocking_bit_gen_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;144;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_mocking_bit_gen_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_mocking_bit_gen_test.exe")
  set_tests_properties(absl_random_mocking_bit_gen_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;144;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_mocking_bit_gen_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_bernoulli_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_bernoulli_distribution_test.exe")
  set_tests_properties(absl_random_bernoulli_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;235;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_bernoulli_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_bernoulli_distribution_test.exe")
  set_tests_properties(absl_random_bernoulli_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;235;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_bernoulli_distribution_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_bernoulli_distribution_test.exe")
  set_tests_properties(absl_random_bernoulli_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;235;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_bernoulli_distribution_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_bernoulli_distribution_test.exe")
  set_tests_properties(absl_random_bernoulli_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;235;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_bernoulli_distribution_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_beta_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_beta_distribution_test.exe")
  set_tests_properties(absl_random_beta_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;253;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_beta_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_beta_distribution_test.exe")
  set_tests_properties(absl_random_beta_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;253;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_beta_distribution_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_beta_distribution_test.exe")
  set_tests_properties(absl_random_beta_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;253;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_beta_distribution_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_beta_distribution_test.exe")
  set_tests_properties(absl_random_beta_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;253;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_beta_distribution_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_distributions_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_distributions_test.exe")
  set_tests_properties(absl_random_distributions_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;276;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_distributions_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_distributions_test.exe")
  set_tests_properties(absl_random_distributions_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;276;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_distributions_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_distributions_test.exe")
  set_tests_properties(absl_random_distributions_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;276;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_distributions_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_distributions_test.exe")
  set_tests_properties(absl_random_distributions_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;276;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_distributions_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_generators_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_generators_test.exe")
  set_tests_properties(absl_random_generators_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;293;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_generators_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_generators_test.exe")
  set_tests_properties(absl_random_generators_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;293;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_generators_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_generators_test.exe")
  set_tests_properties(absl_random_generators_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;293;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_generators_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_generators_test.exe")
  set_tests_properties(absl_random_generators_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;293;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_generators_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_log_uniform_int_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_log_uniform_int_distribution_test.exe")
  set_tests_properties(absl_random_log_uniform_int_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;309;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_log_uniform_int_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_log_uniform_int_distribution_test.exe")
  set_tests_properties(absl_random_log_uniform_int_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;309;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_log_uniform_int_distribution_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_log_uniform_int_distribution_test.exe")
  set_tests_properties(absl_random_log_uniform_int_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;309;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_log_uniform_int_distribution_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_log_uniform_int_distribution_test.exe")
  set_tests_properties(absl_random_log_uniform_int_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;309;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_log_uniform_int_distribution_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_discrete_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_discrete_distribution_test.exe")
  set_tests_properties(absl_random_discrete_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;330;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_discrete_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_discrete_distribution_test.exe")
  set_tests_properties(absl_random_discrete_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;330;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_discrete_distribution_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_discrete_distribution_test.exe")
  set_tests_properties(absl_random_discrete_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;330;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_discrete_distribution_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_discrete_distribution_test.exe")
  set_tests_properties(absl_random_discrete_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;330;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_discrete_distribution_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_poisson_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_poisson_distribution_test.exe")
  set_tests_properties(absl_random_poisson_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;351;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_poisson_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_poisson_distribution_test.exe")
  set_tests_properties(absl_random_poisson_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;351;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_poisson_distribution_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_poisson_distribution_test.exe")
  set_tests_properties(absl_random_poisson_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;351;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_poisson_distribution_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_poisson_distribution_test.exe")
  set_tests_properties(absl_random_poisson_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;351;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_poisson_distribution_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_exponential_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_exponential_distribution_test.exe")
  set_tests_properties(absl_random_exponential_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;375;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_exponential_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_exponential_distribution_test.exe")
  set_tests_properties(absl_random_exponential_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;375;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_exponential_distribution_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_exponential_distribution_test.exe")
  set_tests_properties(absl_random_exponential_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;375;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_exponential_distribution_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_exponential_distribution_test.exe")
  set_tests_properties(absl_random_exponential_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;375;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_exponential_distribution_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_gaussian_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_gaussian_distribution_test.exe")
  set_tests_properties(absl_random_gaussian_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;399;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_gaussian_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_gaussian_distribution_test.exe")
  set_tests_properties(absl_random_gaussian_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;399;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_gaussian_distribution_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_gaussian_distribution_test.exe")
  set_tests_properties(absl_random_gaussian_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;399;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_gaussian_distribution_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_gaussian_distribution_test.exe")
  set_tests_properties(absl_random_gaussian_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;399;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_gaussian_distribution_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_uniform_int_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_uniform_int_distribution_test.exe")
  set_tests_properties(absl_random_uniform_int_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;422;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_uniform_int_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_uniform_int_distribution_test.exe")
  set_tests_properties(absl_random_uniform_int_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;422;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_uniform_int_distribution_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_uniform_int_distribution_test.exe")
  set_tests_properties(absl_random_uniform_int_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;422;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_uniform_int_distribution_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_uniform_int_distribution_test.exe")
  set_tests_properties(absl_random_uniform_int_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;422;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_uniform_int_distribution_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_uniform_real_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_uniform_real_distribution_test.exe")
  set_tests_properties(absl_random_uniform_real_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;443;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_uniform_real_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_uniform_real_distribution_test.exe")
  set_tests_properties(absl_random_uniform_real_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;443;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_uniform_real_distribution_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_uniform_real_distribution_test.exe")
  set_tests_properties(absl_random_uniform_real_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;443;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_uniform_real_distribution_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_uniform_real_distribution_test.exe")
  set_tests_properties(absl_random_uniform_real_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;443;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_uniform_real_distribution_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_zipf_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_zipf_distribution_test.exe")
  set_tests_properties(absl_random_zipf_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;464;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_zipf_distribution_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_zipf_distribution_test.exe")
  set_tests_properties(absl_random_zipf_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;464;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_zipf_distribution_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_zipf_distribution_test.exe")
  set_tests_properties(absl_random_zipf_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;464;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_zipf_distribution_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_zipf_distribution_test.exe")
  set_tests_properties(absl_random_zipf_distribution_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;464;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_zipf_distribution_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_examples_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_examples_test.exe")
  set_tests_properties(absl_random_examples_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;485;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_examples_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_examples_test.exe")
  set_tests_properties(absl_random_examples_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;485;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_examples_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_examples_test.exe")
  set_tests_properties(absl_random_examples_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;485;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_examples_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_examples_test.exe")
  set_tests_properties(absl_random_examples_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;485;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_examples_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_seed_sequences_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_seed_sequences_test.exe")
  set_tests_properties(absl_random_seed_sequences_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;499;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_seed_sequences_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_seed_sequences_test.exe")
  set_tests_properties(absl_random_seed_sequences_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;499;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_seed_sequences_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_seed_sequences_test.exe")
  set_tests_properties(absl_random_seed_sequences_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;499;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_seed_sequences_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_seed_sequences_test.exe")
  set_tests_properties(absl_random_seed_sequences_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;499;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_seed_sequences_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_traits_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_traits_test.exe")
  set_tests_properties(absl_random_internal_traits_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;887;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_traits_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_traits_test.exe")
  set_tests_properties(absl_random_internal_traits_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;887;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_traits_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_traits_test.exe")
  set_tests_properties(absl_random_internal_traits_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;887;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_traits_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_traits_test.exe")
  set_tests_properties(absl_random_internal_traits_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;887;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_traits_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_generate_real_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_generate_real_test.exe")
  set_tests_properties(absl_random_internal_generate_real_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;902;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_generate_real_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_generate_real_test.exe")
  set_tests_properties(absl_random_internal_generate_real_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;902;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_generate_real_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_generate_real_test.exe")
  set_tests_properties(absl_random_internal_generate_real_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;902;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_generate_real_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_generate_real_test.exe")
  set_tests_properties(absl_random_internal_generate_real_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;902;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_generate_real_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_distribution_test_util_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_distribution_test_util_test.exe")
  set_tests_properties(absl_random_internal_distribution_test_util_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;919;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_distribution_test_util_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_distribution_test_util_test.exe")
  set_tests_properties(absl_random_internal_distribution_test_util_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;919;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_distribution_test_util_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_distribution_test_util_test.exe")
  set_tests_properties(absl_random_internal_distribution_test_util_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;919;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_distribution_test_util_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_distribution_test_util_test.exe")
  set_tests_properties(absl_random_internal_distribution_test_util_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;919;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_distribution_test_util_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_fastmath_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_fastmath_test.exe")
  set_tests_properties(absl_random_internal_fastmath_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;934;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_fastmath_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_fastmath_test.exe")
  set_tests_properties(absl_random_internal_fastmath_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;934;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_fastmath_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_fastmath_test.exe")
  set_tests_properties(absl_random_internal_fastmath_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;934;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_fastmath_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_fastmath_test.exe")
  set_tests_properties(absl_random_internal_fastmath_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;934;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_fastmath_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_explicit_seed_seq_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_explicit_seed_seq_test.exe")
  set_tests_properties(absl_random_internal_explicit_seed_seq_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;949;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_explicit_seed_seq_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_explicit_seed_seq_test.exe")
  set_tests_properties(absl_random_internal_explicit_seed_seq_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;949;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_explicit_seed_seq_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_explicit_seed_seq_test.exe")
  set_tests_properties(absl_random_internal_explicit_seed_seq_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;949;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_explicit_seed_seq_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_explicit_seed_seq_test.exe")
  set_tests_properties(absl_random_internal_explicit_seed_seq_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;949;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_explicit_seed_seq_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_salted_seed_seq_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_salted_seed_seq_test.exe")
  set_tests_properties(absl_random_internal_salted_seed_seq_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;966;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_salted_seed_seq_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_salted_seed_seq_test.exe")
  set_tests_properties(absl_random_internal_salted_seed_seq_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;966;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_salted_seed_seq_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_salted_seed_seq_test.exe")
  set_tests_properties(absl_random_internal_salted_seed_seq_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;966;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_salted_seed_seq_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_salted_seed_seq_test.exe")
  set_tests_properties(absl_random_internal_salted_seed_seq_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;966;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_salted_seed_seq_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_chi_square_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_chi_square_test.exe")
  set_tests_properties(absl_random_internal_chi_square_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;982;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_chi_square_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_chi_square_test.exe")
  set_tests_properties(absl_random_internal_chi_square_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;982;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_chi_square_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_chi_square_test.exe")
  set_tests_properties(absl_random_internal_chi_square_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;982;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_chi_square_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_chi_square_test.exe")
  set_tests_properties(absl_random_internal_chi_square_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;982;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_chi_square_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_fast_uniform_bits_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_fast_uniform_bits_test.exe")
  set_tests_properties(absl_random_internal_fast_uniform_bits_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;998;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_fast_uniform_bits_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_fast_uniform_bits_test.exe")
  set_tests_properties(absl_random_internal_fast_uniform_bits_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;998;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_fast_uniform_bits_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_fast_uniform_bits_test.exe")
  set_tests_properties(absl_random_internal_fast_uniform_bits_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;998;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_fast_uniform_bits_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_fast_uniform_bits_test.exe")
  set_tests_properties(absl_random_internal_fast_uniform_bits_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;998;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_fast_uniform_bits_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_nonsecure_base_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_nonsecure_base_test.exe")
  set_tests_properties(absl_random_internal_nonsecure_base_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1013;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_nonsecure_base_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_nonsecure_base_test.exe")
  set_tests_properties(absl_random_internal_nonsecure_base_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1013;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_nonsecure_base_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_nonsecure_base_test.exe")
  set_tests_properties(absl_random_internal_nonsecure_base_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1013;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_nonsecure_base_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_nonsecure_base_test.exe")
  set_tests_properties(absl_random_internal_nonsecure_base_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1013;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_nonsecure_base_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_seed_material_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_seed_material_test.exe")
  set_tests_properties(absl_random_internal_seed_material_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1032;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_seed_material_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_seed_material_test.exe")
  set_tests_properties(absl_random_internal_seed_material_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1032;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_seed_material_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_seed_material_test.exe")
  set_tests_properties(absl_random_internal_seed_material_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1032;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_seed_material_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_seed_material_test.exe")
  set_tests_properties(absl_random_internal_seed_material_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1032;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_seed_material_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_pool_urbg_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_pool_urbg_test.exe")
  set_tests_properties(absl_random_internal_pool_urbg_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1048;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_pool_urbg_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_pool_urbg_test.exe")
  set_tests_properties(absl_random_internal_pool_urbg_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1048;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_pool_urbg_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_pool_urbg_test.exe")
  set_tests_properties(absl_random_internal_pool_urbg_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1048;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_pool_urbg_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_pool_urbg_test.exe")
  set_tests_properties(absl_random_internal_pool_urbg_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1048;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_pool_urbg_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_pcg_engine_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_pcg_engine_test.exe")
  set_tests_properties(absl_random_internal_pcg_engine_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1065;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_pcg_engine_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_pcg_engine_test.exe")
  set_tests_properties(absl_random_internal_pcg_engine_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1065;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_pcg_engine_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_pcg_engine_test.exe")
  set_tests_properties(absl_random_internal_pcg_engine_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1065;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_pcg_engine_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_pcg_engine_test.exe")
  set_tests_properties(absl_random_internal_pcg_engine_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1065;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_pcg_engine_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_randen_engine_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_randen_engine_test.exe")
  set_tests_properties(absl_random_internal_randen_engine_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1083;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_randen_engine_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_randen_engine_test.exe")
  set_tests_properties(absl_random_internal_randen_engine_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1083;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_randen_engine_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_randen_engine_test.exe")
  set_tests_properties(absl_random_internal_randen_engine_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1083;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_randen_engine_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_randen_engine_test.exe")
  set_tests_properties(absl_random_internal_randen_engine_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1083;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_randen_engine_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_randen_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_randen_test.exe")
  set_tests_properties(absl_random_internal_randen_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1103;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_randen_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_randen_test.exe")
  set_tests_properties(absl_random_internal_randen_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1103;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_randen_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_randen_test.exe")
  set_tests_properties(absl_random_internal_randen_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1103;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_randen_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_randen_test.exe")
  set_tests_properties(absl_random_internal_randen_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1103;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_randen_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_randen_slow_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_randen_slow_test.exe")
  set_tests_properties(absl_random_internal_randen_slow_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1119;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_randen_slow_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_randen_slow_test.exe")
  set_tests_properties(absl_random_internal_randen_slow_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1119;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_randen_slow_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_randen_slow_test.exe")
  set_tests_properties(absl_random_internal_randen_slow_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1119;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_randen_slow_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_randen_slow_test.exe")
  set_tests_properties(absl_random_internal_randen_slow_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1119;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_randen_slow_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_randen_hwaes_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_randen_hwaes_test.exe")
  set_tests_properties(absl_random_internal_randen_hwaes_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1135;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_randen_hwaes_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_randen_hwaes_test.exe")
  set_tests_properties(absl_random_internal_randen_hwaes_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1135;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_randen_hwaes_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_randen_hwaes_test.exe")
  set_tests_properties(absl_random_internal_randen_hwaes_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1135;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_randen_hwaes_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_randen_hwaes_test.exe")
  set_tests_properties(absl_random_internal_randen_hwaes_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1135;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_randen_hwaes_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_uniform_helper_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_uniform_helper_test.exe")
  set_tests_properties(absl_random_internal_uniform_helper_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1171;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_uniform_helper_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_uniform_helper_test.exe")
  set_tests_properties(absl_random_internal_uniform_helper_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1171;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_uniform_helper_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_uniform_helper_test.exe")
  set_tests_properties(absl_random_internal_uniform_helper_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1171;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_uniform_helper_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_uniform_helper_test.exe")
  set_tests_properties(absl_random_internal_uniform_helper_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1171;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_uniform_helper_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_iostream_state_saver_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_iostream_state_saver_test.exe")
  set_tests_properties(absl_random_internal_iostream_state_saver_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1186;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_iostream_state_saver_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_iostream_state_saver_test.exe")
  set_tests_properties(absl_random_internal_iostream_state_saver_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1186;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_iostream_state_saver_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_iostream_state_saver_test.exe")
  set_tests_properties(absl_random_internal_iostream_state_saver_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1186;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_iostream_state_saver_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_iostream_state_saver_test.exe")
  set_tests_properties(absl_random_internal_iostream_state_saver_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1186;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_iostream_state_saver_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_random_internal_wide_multiply_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_random_internal_wide_multiply_test.exe")
  set_tests_properties(absl_random_internal_wide_multiply_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1201;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_random_internal_wide_multiply_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_random_internal_wide_multiply_test.exe")
  set_tests_properties(absl_random_internal_wide_multiply_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1201;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_random_internal_wide_multiply_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_random_internal_wide_multiply_test.exe")
  set_tests_properties(absl_random_internal_wide_multiply_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1201;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_random_internal_wide_multiply_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_random_internal_wide_multiply_test.exe")
  set_tests_properties(absl_random_internal_wide_multiply_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;1201;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/random/CMakeLists.txt;0;")
else()
  add_test(absl_random_internal_wide_multiply_test NOT_AVAILABLE)
endif()
