# CMake generated Testfile for 
# Source directory: C:/git/library/abseil/abseil-cpp/absl/crc
# Build directory: C:/git/library/abseil/abseil-cpp/absl/crc
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_crc32c_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_crc32c_test.exe")
  set_tests_properties(absl_crc32c_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;83;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_crc32c_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_crc32c_test.exe")
  set_tests_properties(absl_crc32c_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;83;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_crc32c_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_crc32c_test.exe")
  set_tests_properties(absl_crc32c_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;83;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_crc32c_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_crc32c_test.exe")
  set_tests_properties(absl_crc32c_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;83;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;0;")
else()
  add_test(absl_crc32c_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_crc_memcpy_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_crc_memcpy_test.exe")
  set_tests_properties(absl_crc_memcpy_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;122;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_crc_memcpy_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_crc_memcpy_test.exe")
  set_tests_properties(absl_crc_memcpy_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;122;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_crc_memcpy_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_crc_memcpy_test.exe")
  set_tests_properties(absl_crc_memcpy_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;122;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_crc_memcpy_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_crc_memcpy_test.exe")
  set_tests_properties(absl_crc_memcpy_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;122;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;0;")
else()
  add_test(absl_crc_memcpy_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_non_temporal_memcpy_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_non_temporal_memcpy_test.exe")
  set_tests_properties(absl_non_temporal_memcpy_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;138;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_non_temporal_memcpy_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_non_temporal_memcpy_test.exe")
  set_tests_properties(absl_non_temporal_memcpy_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;138;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_non_temporal_memcpy_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_non_temporal_memcpy_test.exe")
  set_tests_properties(absl_non_temporal_memcpy_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;138;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_non_temporal_memcpy_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_non_temporal_memcpy_test.exe")
  set_tests_properties(absl_non_temporal_memcpy_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;138;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;0;")
else()
  add_test(absl_non_temporal_memcpy_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_crc_cord_state_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_crc_cord_state_test.exe")
  set_tests_properties(absl_crc_cord_state_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;165;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_crc_cord_state_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_crc_cord_state_test.exe")
  set_tests_properties(absl_crc_cord_state_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;165;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_crc_cord_state_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_crc_cord_state_test.exe")
  set_tests_properties(absl_crc_cord_state_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;165;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_crc_cord_state_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_crc_cord_state_test.exe")
  set_tests_properties(absl_crc_cord_state_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;165;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/crc/CMakeLists.txt;0;")
else()
  add_test(absl_crc_cord_state_test NOT_AVAILABLE)
endif()
