# CMake generated Testfile for 
# Source directory: C:/git/library/abseil/abseil-cpp/absl/container
# Build directory: C:/git/library/abseil/abseil-cpp/absl/container
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_btree_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_btree_test.exe")
  set_tests_properties(absl_btree_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;65;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_btree_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_btree_test.exe")
  set_tests_properties(absl_btree_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;65;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_btree_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_btree_test.exe")
  set_tests_properties(absl_btree_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;65;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_btree_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_btree_test.exe")
  set_tests_properties(absl_btree_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;65;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_btree_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_compressed_tuple_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_compressed_tuple_test.exe")
  set_tests_properties(absl_compressed_tuple_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;104;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_compressed_tuple_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_compressed_tuple_test.exe")
  set_tests_properties(absl_compressed_tuple_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;104;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_compressed_tuple_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_compressed_tuple_test.exe")
  set_tests_properties(absl_compressed_tuple_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;104;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_compressed_tuple_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_compressed_tuple_test.exe")
  set_tests_properties(absl_compressed_tuple_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;104;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_compressed_tuple_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_fixed_array_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_fixed_array_test.exe")
  set_tests_properties(absl_fixed_array_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;139;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_fixed_array_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_fixed_array_test.exe")
  set_tests_properties(absl_fixed_array_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;139;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_fixed_array_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_fixed_array_test.exe")
  set_tests_properties(absl_fixed_array_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;139;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_fixed_array_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_fixed_array_test.exe")
  set_tests_properties(absl_fixed_array_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;139;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_fixed_array_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_fixed_array_exception_safety_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_fixed_array_exception_safety_test.exe")
  set_tests_properties(absl_fixed_array_exception_safety_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;156;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_fixed_array_exception_safety_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_fixed_array_exception_safety_test.exe")
  set_tests_properties(absl_fixed_array_exception_safety_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;156;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_fixed_array_exception_safety_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_fixed_array_exception_safety_test.exe")
  set_tests_properties(absl_fixed_array_exception_safety_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;156;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_fixed_array_exception_safety_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_fixed_array_exception_safety_test.exe")
  set_tests_properties(absl_fixed_array_exception_safety_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;156;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_fixed_array_exception_safety_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_inlined_vector_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_inlined_vector_test.exe")
  set_tests_properties(absl_inlined_vector_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;216;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_inlined_vector_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_inlined_vector_test.exe")
  set_tests_properties(absl_inlined_vector_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;216;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_inlined_vector_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_inlined_vector_test.exe")
  set_tests_properties(absl_inlined_vector_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;216;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_inlined_vector_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_inlined_vector_test.exe")
  set_tests_properties(absl_inlined_vector_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;216;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_inlined_vector_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_inlined_vector_exception_safety_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_inlined_vector_exception_safety_test.exe")
  set_tests_properties(absl_inlined_vector_exception_safety_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;237;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_inlined_vector_exception_safety_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_inlined_vector_exception_safety_test.exe")
  set_tests_properties(absl_inlined_vector_exception_safety_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;237;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_inlined_vector_exception_safety_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_inlined_vector_exception_safety_test.exe")
  set_tests_properties(absl_inlined_vector_exception_safety_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;237;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_inlined_vector_exception_safety_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_inlined_vector_exception_safety_test.exe")
  set_tests_properties(absl_inlined_vector_exception_safety_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;237;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_inlined_vector_exception_safety_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_test_instance_tracker_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_test_instance_tracker_test.exe")
  set_tests_properties(absl_test_instance_tracker_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;266;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_test_instance_tracker_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_test_instance_tracker_test.exe")
  set_tests_properties(absl_test_instance_tracker_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;266;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_test_instance_tracker_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_test_instance_tracker_test.exe")
  set_tests_properties(absl_test_instance_tracker_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;266;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_test_instance_tracker_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_test_instance_tracker_test.exe")
  set_tests_properties(absl_test_instance_tracker_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;266;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_test_instance_tracker_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_flat_hash_map_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_flat_hash_map_test.exe")
  set_tests_properties(absl_flat_hash_map_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;295;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_flat_hash_map_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_flat_hash_map_test.exe")
  set_tests_properties(absl_flat_hash_map_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;295;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_flat_hash_map_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_flat_hash_map_test.exe")
  set_tests_properties(absl_flat_hash_map_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;295;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_flat_hash_map_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_flat_hash_map_test.exe")
  set_tests_properties(absl_flat_hash_map_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;295;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_flat_hash_map_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_flat_hash_set_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_flat_hash_set_test.exe")
  set_tests_properties(absl_flat_hash_set_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;331;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_flat_hash_set_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_flat_hash_set_test.exe")
  set_tests_properties(absl_flat_hash_set_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;331;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_flat_hash_set_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_flat_hash_set_test.exe")
  set_tests_properties(absl_flat_hash_set_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;331;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_flat_hash_set_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_flat_hash_set_test.exe")
  set_tests_properties(absl_flat_hash_set_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;331;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_flat_hash_set_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_node_hash_map_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_node_hash_map_test.exe")
  set_tests_properties(absl_node_hash_map_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;370;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_node_hash_map_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_node_hash_map_test.exe")
  set_tests_properties(absl_node_hash_map_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;370;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_node_hash_map_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_node_hash_map_test.exe")
  set_tests_properties(absl_node_hash_map_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;370;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_node_hash_map_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_node_hash_map_test.exe")
  set_tests_properties(absl_node_hash_map_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;370;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_node_hash_map_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_node_hash_set_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_node_hash_set_test.exe")
  set_tests_properties(absl_node_hash_set_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;405;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_node_hash_set_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_node_hash_set_test.exe")
  set_tests_properties(absl_node_hash_set_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;405;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_node_hash_set_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_node_hash_set_test.exe")
  set_tests_properties(absl_node_hash_set_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;405;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_node_hash_set_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_node_hash_set_test.exe")
  set_tests_properties(absl_node_hash_set_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;405;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_node_hash_set_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_container_memory_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_container_memory_test.exe")
  set_tests_properties(absl_container_memory_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;439;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_container_memory_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_container_memory_test.exe")
  set_tests_properties(absl_container_memory_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;439;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_container_memory_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_container_memory_test.exe")
  set_tests_properties(absl_container_memory_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;439;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_container_memory_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_container_memory_test.exe")
  set_tests_properties(absl_container_memory_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;439;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_container_memory_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_hash_function_defaults_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_hash_function_defaults_test.exe")
  set_tests_properties(absl_hash_function_defaults_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;469;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_hash_function_defaults_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_hash_function_defaults_test.exe")
  set_tests_properties(absl_hash_function_defaults_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;469;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_hash_function_defaults_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_hash_function_defaults_test.exe")
  set_tests_properties(absl_hash_function_defaults_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;469;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_hash_function_defaults_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_hash_function_defaults_test.exe")
  set_tests_properties(absl_hash_function_defaults_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;469;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_hash_function_defaults_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_hash_policy_testing_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_hash_policy_testing_test.exe")
  set_tests_properties(absl_hash_policy_testing_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;518;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_hash_policy_testing_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_hash_policy_testing_test.exe")
  set_tests_properties(absl_hash_policy_testing_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;518;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_hash_policy_testing_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_hash_policy_testing_test.exe")
  set_tests_properties(absl_hash_policy_testing_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;518;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_hash_policy_testing_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_hash_policy_testing_test.exe")
  set_tests_properties(absl_hash_policy_testing_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;518;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_hash_policy_testing_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_hash_policy_traits_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_hash_policy_traits_test.exe")
  set_tests_properties(absl_hash_policy_traits_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;544;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_hash_policy_traits_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_hash_policy_traits_test.exe")
  set_tests_properties(absl_hash_policy_traits_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;544;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_hash_policy_traits_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_hash_policy_traits_test.exe")
  set_tests_properties(absl_hash_policy_traits_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;544;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_hash_policy_traits_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_hash_policy_traits_test.exe")
  set_tests_properties(absl_hash_policy_traits_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;544;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_hash_policy_traits_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_common_policy_traits_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_common_policy_traits_test.exe")
  set_tests_properties(absl_common_policy_traits_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;569;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_common_policy_traits_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_common_policy_traits_test.exe")
  set_tests_properties(absl_common_policy_traits_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;569;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_common_policy_traits_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_common_policy_traits_test.exe")
  set_tests_properties(absl_common_policy_traits_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;569;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_common_policy_traits_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_common_policy_traits_test.exe")
  set_tests_properties(absl_common_policy_traits_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;569;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_common_policy_traits_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_hashtablez_sampler_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_hashtablez_sampler_test.exe")
  set_tests_properties(absl_hashtablez_sampler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;602;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_hashtablez_sampler_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_hashtablez_sampler_test.exe")
  set_tests_properties(absl_hashtablez_sampler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;602;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_hashtablez_sampler_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_hashtablez_sampler_test.exe")
  set_tests_properties(absl_hashtablez_sampler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;602;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_hashtablez_sampler_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_hashtablez_sampler_test.exe")
  set_tests_properties(absl_hashtablez_sampler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;602;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_hashtablez_sampler_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_node_slot_policy_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_node_slot_policy_test.exe")
  set_tests_properties(absl_node_slot_policy_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;653;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_node_slot_policy_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_node_slot_policy_test.exe")
  set_tests_properties(absl_node_slot_policy_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;653;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_node_slot_policy_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_node_slot_policy_test.exe")
  set_tests_properties(absl_node_slot_policy_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;653;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_node_slot_policy_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_node_slot_policy_test.exe")
  set_tests_properties(absl_node_slot_policy_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;653;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_node_slot_policy_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_raw_hash_set_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_raw_hash_set_test.exe")
  set_tests_properties(absl_raw_hash_set_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;725;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_raw_hash_set_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_raw_hash_set_test.exe")
  set_tests_properties(absl_raw_hash_set_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;725;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_raw_hash_set_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_raw_hash_set_test.exe")
  set_tests_properties(absl_raw_hash_set_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;725;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_raw_hash_set_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_raw_hash_set_test.exe")
  set_tests_properties(absl_raw_hash_set_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;725;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_raw_hash_set_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_raw_hash_set_allocator_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_raw_hash_set_allocator_test.exe")
  set_tests_properties(absl_raw_hash_set_allocator_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;750;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_raw_hash_set_allocator_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_raw_hash_set_allocator_test.exe")
  set_tests_properties(absl_raw_hash_set_allocator_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;750;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_raw_hash_set_allocator_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_raw_hash_set_allocator_test.exe")
  set_tests_properties(absl_raw_hash_set_allocator_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;750;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_raw_hash_set_allocator_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_raw_hash_set_allocator_test.exe")
  set_tests_properties(absl_raw_hash_set_allocator_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;750;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_raw_hash_set_allocator_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_layout_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_layout_test.exe")
  set_tests_properties(absl_layout_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;782;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_layout_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_layout_test.exe")
  set_tests_properties(absl_layout_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;782;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_layout_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_layout_test.exe")
  set_tests_properties(absl_layout_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;782;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_layout_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_layout_test.exe")
  set_tests_properties(absl_layout_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;782;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_layout_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_unordered_set_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_unordered_set_test.exe")
  set_tests_properties(absl_unordered_set_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;929;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_unordered_set_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_unordered_set_test.exe")
  set_tests_properties(absl_unordered_set_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;929;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_unordered_set_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_unordered_set_test.exe")
  set_tests_properties(absl_unordered_set_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;929;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_unordered_set_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_unordered_set_test.exe")
  set_tests_properties(absl_unordered_set_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;929;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_unordered_set_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_unordered_map_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_unordered_map_test.exe")
  set_tests_properties(absl_unordered_map_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;944;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_unordered_map_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_unordered_map_test.exe")
  set_tests_properties(absl_unordered_map_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;944;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_unordered_map_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_unordered_map_test.exe")
  set_tests_properties(absl_unordered_map_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;944;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_unordered_map_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_unordered_map_test.exe")
  set_tests_properties(absl_unordered_map_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;944;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_unordered_map_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_sample_element_size_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_sample_element_size_test.exe")
  set_tests_properties(absl_sample_element_size_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;959;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_sample_element_size_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_sample_element_size_test.exe")
  set_tests_properties(absl_sample_element_size_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;959;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_sample_element_size_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_sample_element_size_test.exe")
  set_tests_properties(absl_sample_element_size_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;959;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_sample_element_size_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_sample_element_size_test.exe")
  set_tests_properties(absl_sample_element_size_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;959;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/container/CMakeLists.txt;0;")
else()
  add_test(absl_sample_element_size_test NOT_AVAILABLE)
endif()
