# CMake generated Testfile for 
# Source directory: C:/git/library/abseil/abseil-cpp/absl/debugging
# Build directory: C:/git/library/abseil/abseil-cpp/absl/debugging
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_stacktrace_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_stacktrace_test.exe")
  set_tests_properties(absl_stacktrace_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;48;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_stacktrace_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_stacktrace_test.exe")
  set_tests_properties(absl_stacktrace_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;48;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_stacktrace_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_stacktrace_test.exe")
  set_tests_properties(absl_stacktrace_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;48;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_stacktrace_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_stacktrace_test.exe")
  set_tests_properties(absl_stacktrace_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;48;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
else()
  add_test(absl_stacktrace_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_symbolize_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_symbolize_test.exe")
  set_tests_properties(absl_symbolize_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;92;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_symbolize_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_symbolize_test.exe")
  set_tests_properties(absl_symbolize_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;92;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_symbolize_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_symbolize_test.exe")
  set_tests_properties(absl_symbolize_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;92;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_symbolize_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_symbolize_test.exe")
  set_tests_properties(absl_symbolize_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;92;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
else()
  add_test(absl_symbolize_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_failure_signal_handler_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_failure_signal_handler_test.exe")
  set_tests_properties(absl_failure_signal_handler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;151;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_failure_signal_handler_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_failure_signal_handler_test.exe")
  set_tests_properties(absl_failure_signal_handler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;151;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_failure_signal_handler_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_failure_signal_handler_test.exe")
  set_tests_properties(absl_failure_signal_handler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;151;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_failure_signal_handler_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_failure_signal_handler_test.exe")
  set_tests_properties(absl_failure_signal_handler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;151;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
else()
  add_test(absl_failure_signal_handler_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_demangle_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_demangle_test.exe")
  set_tests_properties(absl_demangle_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;206;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_demangle_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_demangle_test.exe")
  set_tests_properties(absl_demangle_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;206;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_demangle_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_demangle_test.exe")
  set_tests_properties(absl_demangle_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;206;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_demangle_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_demangle_test.exe")
  set_tests_properties(absl_demangle_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;206;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
else()
  add_test(absl_demangle_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_leak_check_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_leak_check_test.exe")
  set_tests_properties(absl_leak_check_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;238;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_leak_check_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_leak_check_test.exe")
  set_tests_properties(absl_leak_check_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;238;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_leak_check_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_leak_check_test.exe")
  set_tests_properties(absl_leak_check_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;238;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_leak_check_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_leak_check_test.exe")
  set_tests_properties(absl_leak_check_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;238;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
else()
  add_test(absl_leak_check_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_stack_consumption_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_stack_consumption_test.exe")
  set_tests_properties(absl_stack_consumption_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;270;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_stack_consumption_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_stack_consumption_test.exe")
  set_tests_properties(absl_stack_consumption_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;270;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_stack_consumption_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_stack_consumption_test.exe")
  set_tests_properties(absl_stack_consumption_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;270;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_stack_consumption_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_stack_consumption_test.exe")
  set_tests_properties(absl_stack_consumption_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;270;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/debugging/CMakeLists.txt;0;")
else()
  add_test(absl_stack_consumption_test NOT_AVAILABLE)
endif()
