# CMake generated Testfile for 
# Source directory: C:/git/library/abseil/abseil-cpp/absl/flags
# Build directory: C:/git/library/abseil/abseil-cpp/absl/flags
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_flags_commandlineflag_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_flags_commandlineflag_test.exe")
  set_tests_properties(absl_flags_commandlineflag_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;302;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_flags_commandlineflag_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_flags_commandlineflag_test.exe")
  set_tests_properties(absl_flags_commandlineflag_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;302;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_flags_commandlineflag_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_flags_commandlineflag_test.exe")
  set_tests_properties(absl_flags_commandlineflag_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;302;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_flags_commandlineflag_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_flags_commandlineflag_test.exe")
  set_tests_properties(absl_flags_commandlineflag_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;302;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
else()
  add_test(absl_flags_commandlineflag_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_flags_config_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_flags_config_test.exe")
  set_tests_properties(absl_flags_config_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;321;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_flags_config_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_flags_config_test.exe")
  set_tests_properties(absl_flags_config_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;321;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_flags_config_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_flags_config_test.exe")
  set_tests_properties(absl_flags_config_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;321;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_flags_config_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_flags_config_test.exe")
  set_tests_properties(absl_flags_config_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;321;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
else()
  add_test(absl_flags_config_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_flags_flag_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_flags_flag_test.exe")
  set_tests_properties(absl_flags_flag_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;333;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_flags_flag_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_flags_flag_test.exe")
  set_tests_properties(absl_flags_flag_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;333;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_flags_flag_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_flags_flag_test.exe")
  set_tests_properties(absl_flags_flag_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;333;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_flags_flag_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_flags_flag_test.exe")
  set_tests_properties(absl_flags_flag_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;333;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
else()
  add_test(absl_flags_flag_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_flags_marshalling_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_flags_marshalling_test.exe")
  set_tests_properties(absl_flags_marshalling_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;353;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_flags_marshalling_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_flags_marshalling_test.exe")
  set_tests_properties(absl_flags_marshalling_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;353;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_flags_marshalling_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_flags_marshalling_test.exe")
  set_tests_properties(absl_flags_marshalling_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;353;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_flags_marshalling_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_flags_marshalling_test.exe")
  set_tests_properties(absl_flags_marshalling_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;353;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
else()
  add_test(absl_flags_marshalling_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_flags_parse_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_flags_parse_test.exe")
  set_tests_properties(absl_flags_parse_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;365;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_flags_parse_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_flags_parse_test.exe")
  set_tests_properties(absl_flags_parse_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;365;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_flags_parse_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_flags_parse_test.exe")
  set_tests_properties(absl_flags_parse_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;365;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_flags_parse_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_flags_parse_test.exe")
  set_tests_properties(absl_flags_parse_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;365;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
else()
  add_test(absl_flags_parse_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_flags_path_util_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_flags_path_util_test.exe")
  set_tests_properties(absl_flags_path_util_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;384;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_flags_path_util_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_flags_path_util_test.exe")
  set_tests_properties(absl_flags_path_util_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;384;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_flags_path_util_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_flags_path_util_test.exe")
  set_tests_properties(absl_flags_path_util_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;384;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_flags_path_util_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_flags_path_util_test.exe")
  set_tests_properties(absl_flags_path_util_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;384;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
else()
  add_test(absl_flags_path_util_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_flags_program_name_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_flags_program_name_test.exe")
  set_tests_properties(absl_flags_program_name_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;396;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_flags_program_name_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_flags_program_name_test.exe")
  set_tests_properties(absl_flags_program_name_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;396;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_flags_program_name_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_flags_program_name_test.exe")
  set_tests_properties(absl_flags_program_name_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;396;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_flags_program_name_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_flags_program_name_test.exe")
  set_tests_properties(absl_flags_program_name_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;396;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
else()
  add_test(absl_flags_program_name_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_flags_reflection_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_flags_reflection_test.exe")
  set_tests_properties(absl_flags_reflection_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;409;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_flags_reflection_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_flags_reflection_test.exe")
  set_tests_properties(absl_flags_reflection_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;409;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_flags_reflection_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_flags_reflection_test.exe")
  set_tests_properties(absl_flags_reflection_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;409;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_flags_reflection_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_flags_reflection_test.exe")
  set_tests_properties(absl_flags_reflection_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;409;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
else()
  add_test(absl_flags_reflection_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_flags_sequence_lock_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_flags_sequence_lock_test.exe")
  set_tests_properties(absl_flags_sequence_lock_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;426;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_flags_sequence_lock_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_flags_sequence_lock_test.exe")
  set_tests_properties(absl_flags_sequence_lock_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;426;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_flags_sequence_lock_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_flags_sequence_lock_test.exe")
  set_tests_properties(absl_flags_sequence_lock_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;426;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_flags_sequence_lock_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_flags_sequence_lock_test.exe")
  set_tests_properties(absl_flags_sequence_lock_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;426;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
else()
  add_test(absl_flags_sequence_lock_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_flags_usage_config_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_flags_usage_config_test.exe")
  set_tests_properties(absl_flags_usage_config_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;440;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_flags_usage_config_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_flags_usage_config_test.exe")
  set_tests_properties(absl_flags_usage_config_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;440;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_flags_usage_config_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_flags_usage_config_test.exe")
  set_tests_properties(absl_flags_usage_config_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;440;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_flags_usage_config_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_flags_usage_config_test.exe")
  set_tests_properties(absl_flags_usage_config_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;440;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
else()
  add_test(absl_flags_usage_config_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_flags_usage_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_flags_usage_test.exe")
  set_tests_properties(absl_flags_usage_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;455;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_flags_usage_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_flags_usage_test.exe")
  set_tests_properties(absl_flags_usage_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;455;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_flags_usage_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_flags_usage_test.exe")
  set_tests_properties(absl_flags_usage_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;455;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_flags_usage_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_flags_usage_test.exe")
  set_tests_properties(absl_flags_usage_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;455;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/flags/CMakeLists.txt;0;")
else()
  add_test(absl_flags_usage_test NOT_AVAILABLE)
endif()
