# CMake generated Testfile for 
# Source directory: C:/git/library/abseil/abseil-cpp/absl/functional
# Build directory: C:/git/library/abseil/abseil-cpp/absl/functional
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_any_invocable_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_any_invocable_test.exe")
  set_tests_properties(absl_any_invocable_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;35;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_any_invocable_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_any_invocable_test.exe")
  set_tests_properties(absl_any_invocable_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;35;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_any_invocable_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_any_invocable_test.exe")
  set_tests_properties(absl_any_invocable_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;35;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_any_invocable_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_any_invocable_test.exe")
  set_tests_properties(absl_any_invocable_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;35;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;0;")
else()
  add_test(absl_any_invocable_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_bind_front_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_bind_front_test.exe")
  set_tests_properties(absl_bind_front_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;68;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_bind_front_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_bind_front_test.exe")
  set_tests_properties(absl_bind_front_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;68;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_bind_front_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_bind_front_test.exe")
  set_tests_properties(absl_bind_front_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;68;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_bind_front_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_bind_front_test.exe")
  set_tests_properties(absl_bind_front_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;68;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;0;")
else()
  add_test(absl_bind_front_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_function_ref_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_function_ref_test.exe")
  set_tests_properties(absl_function_ref_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;97;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_function_ref_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_function_ref_test.exe")
  set_tests_properties(absl_function_ref_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;97;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_function_ref_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_function_ref_test.exe")
  set_tests_properties(absl_function_ref_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;97;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_function_ref_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_function_ref_test.exe")
  set_tests_properties(absl_function_ref_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;97;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/functional/CMakeLists.txt;0;")
else()
  add_test(absl_function_ref_test NOT_AVAILABLE)
endif()
