# CMake generated Testfile for 
# Source directory: C:/git/library/abseil/abseil-cpp/absl/base
# Build directory: C:/git/library/abseil/abseil-cpp/absl/base
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_absl_exception_safety_testing_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_absl_exception_safety_testing_test.exe")
  set_tests_properties(absl_absl_exception_safety_testing_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;279;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_absl_exception_safety_testing_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_absl_exception_safety_testing_test.exe")
  set_tests_properties(absl_absl_exception_safety_testing_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;279;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_absl_exception_safety_testing_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_absl_exception_safety_testing_test.exe")
  set_tests_properties(absl_absl_exception_safety_testing_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;279;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_absl_exception_safety_testing_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_absl_exception_safety_testing_test.exe")
  set_tests_properties(absl_absl_exception_safety_testing_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;279;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_absl_exception_safety_testing_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_atomic_hook_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_atomic_hook_test.exe")
  set_tests_properties(absl_atomic_hook_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;306;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_atomic_hook_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_atomic_hook_test.exe")
  set_tests_properties(absl_atomic_hook_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;306;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_atomic_hook_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_atomic_hook_test.exe")
  set_tests_properties(absl_atomic_hook_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;306;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_atomic_hook_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_atomic_hook_test.exe")
  set_tests_properties(absl_atomic_hook_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;306;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_atomic_hook_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_bit_cast_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_bit_cast_test.exe")
  set_tests_properties(absl_bit_cast_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;321;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_bit_cast_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_bit_cast_test.exe")
  set_tests_properties(absl_bit_cast_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;321;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_bit_cast_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_bit_cast_test.exe")
  set_tests_properties(absl_bit_cast_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;321;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_bit_cast_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_bit_cast_test.exe")
  set_tests_properties(absl_bit_cast_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;321;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_bit_cast_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_errno_saver_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_errno_saver_test.exe")
  set_tests_properties(absl_errno_saver_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;334;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_errno_saver_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_errno_saver_test.exe")
  set_tests_properties(absl_errno_saver_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;334;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_errno_saver_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_errno_saver_test.exe")
  set_tests_properties(absl_errno_saver_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;334;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_errno_saver_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_errno_saver_test.exe")
  set_tests_properties(absl_errno_saver_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;334;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_errno_saver_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_throw_delegate_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_throw_delegate_test.exe")
  set_tests_properties(absl_throw_delegate_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;348;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_throw_delegate_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_throw_delegate_test.exe")
  set_tests_properties(absl_throw_delegate_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;348;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_throw_delegate_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_throw_delegate_test.exe")
  set_tests_properties(absl_throw_delegate_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;348;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_throw_delegate_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_throw_delegate_test.exe")
  set_tests_properties(absl_throw_delegate_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;348;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_throw_delegate_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_inline_variable_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_inline_variable_test.exe")
  set_tests_properties(absl_inline_variable_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;362;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_inline_variable_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_inline_variable_test.exe")
  set_tests_properties(absl_inline_variable_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;362;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_inline_variable_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_inline_variable_test.exe")
  set_tests_properties(absl_inline_variable_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;362;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_inline_variable_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_inline_variable_test.exe")
  set_tests_properties(absl_inline_variable_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;362;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_inline_variable_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_invoke_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_invoke_test.exe")
  set_tests_properties(absl_invoke_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;377;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_invoke_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_invoke_test.exe")
  set_tests_properties(absl_invoke_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;377;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_invoke_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_invoke_test.exe")
  set_tests_properties(absl_invoke_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;377;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_invoke_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_invoke_test.exe")
  set_tests_properties(absl_invoke_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;377;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_invoke_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_spinlock_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_spinlock_test.exe")
  set_tests_properties(absl_spinlock_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;411;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_spinlock_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_spinlock_test.exe")
  set_tests_properties(absl_spinlock_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;411;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_spinlock_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_spinlock_test.exe")
  set_tests_properties(absl_spinlock_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;411;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_spinlock_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_spinlock_test.exe")
  set_tests_properties(absl_spinlock_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;411;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_spinlock_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_endian_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_endian_test.exe")
  set_tests_properties(absl_endian_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;443;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_endian_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_endian_test.exe")
  set_tests_properties(absl_endian_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;443;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_endian_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_endian_test.exe")
  set_tests_properties(absl_endian_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;443;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_endian_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_endian_test.exe")
  set_tests_properties(absl_endian_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;443;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_endian_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_config_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_config_test.exe")
  set_tests_properties(absl_config_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;457;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_config_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_config_test.exe")
  set_tests_properties(absl_config_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;457;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_config_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_config_test.exe")
  set_tests_properties(absl_config_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;457;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_config_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_config_test.exe")
  set_tests_properties(absl_config_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;457;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_config_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_call_once_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_call_once_test.exe")
  set_tests_properties(absl_call_once_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;470;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_call_once_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_call_once_test.exe")
  set_tests_properties(absl_call_once_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;470;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_call_once_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_call_once_test.exe")
  set_tests_properties(absl_call_once_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;470;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_call_once_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_call_once_test.exe")
  set_tests_properties(absl_call_once_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;470;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_call_once_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_raw_logging_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_raw_logging_test.exe")
  set_tests_properties(absl_raw_logging_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;484;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_raw_logging_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_raw_logging_test.exe")
  set_tests_properties(absl_raw_logging_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;484;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_raw_logging_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_raw_logging_test.exe")
  set_tests_properties(absl_raw_logging_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;484;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_raw_logging_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_raw_logging_test.exe")
  set_tests_properties(absl_raw_logging_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;484;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_raw_logging_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_sysinfo_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_sysinfo_test.exe")
  set_tests_properties(absl_sysinfo_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;497;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_sysinfo_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_sysinfo_test.exe")
  set_tests_properties(absl_sysinfo_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;497;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_sysinfo_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_sysinfo_test.exe")
  set_tests_properties(absl_sysinfo_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;497;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_sysinfo_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_sysinfo_test.exe")
  set_tests_properties(absl_sysinfo_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;497;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_sysinfo_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_low_level_alloc_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_low_level_alloc_test.exe")
  set_tests_properties(absl_low_level_alloc_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;510;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_low_level_alloc_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_low_level_alloc_test.exe")
  set_tests_properties(absl_low_level_alloc_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;510;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_low_level_alloc_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_low_level_alloc_test.exe")
  set_tests_properties(absl_low_level_alloc_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;510;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_low_level_alloc_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_low_level_alloc_test.exe")
  set_tests_properties(absl_low_level_alloc_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;510;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_low_level_alloc_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_thread_identity_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_thread_identity_test.exe")
  set_tests_properties(absl_thread_identity_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;523;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_thread_identity_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_thread_identity_test.exe")
  set_tests_properties(absl_thread_identity_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;523;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_thread_identity_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_thread_identity_test.exe")
  set_tests_properties(absl_thread_identity_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;523;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_thread_identity_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_thread_identity_test.exe")
  set_tests_properties(absl_thread_identity_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;523;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_thread_identity_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_scoped_set_env_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_scoped_set_env_test.exe")
  set_tests_properties(absl_scoped_set_env_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;553;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_scoped_set_env_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_scoped_set_env_test.exe")
  set_tests_properties(absl_scoped_set_env_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;553;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_scoped_set_env_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_scoped_set_env_test.exe")
  set_tests_properties(absl_scoped_set_env_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;553;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_scoped_set_env_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_scoped_set_env_test.exe")
  set_tests_properties(absl_scoped_set_env_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;553;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_scoped_set_env_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_cmake_thread_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_cmake_thread_test.exe")
  set_tests_properties(absl_cmake_thread_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;565;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_cmake_thread_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_cmake_thread_test.exe")
  set_tests_properties(absl_cmake_thread_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;565;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_cmake_thread_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_cmake_thread_test.exe")
  set_tests_properties(absl_cmake_thread_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;565;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_cmake_thread_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_cmake_thread_test.exe")
  set_tests_properties(absl_cmake_thread_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;565;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_cmake_thread_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_log_severity_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_log_severity_test.exe")
  set_tests_properties(absl_log_severity_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;576;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_log_severity_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_log_severity_test.exe")
  set_tests_properties(absl_log_severity_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;576;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_log_severity_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_log_severity_test.exe")
  set_tests_properties(absl_log_severity_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;576;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_log_severity_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_log_severity_test.exe")
  set_tests_properties(absl_log_severity_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;576;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_log_severity_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_strerror_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_strerror_test.exe")
  set_tests_properties(absl_strerror_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;608;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_strerror_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_strerror_test.exe")
  set_tests_properties(absl_strerror_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;608;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_strerror_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_strerror_test.exe")
  set_tests_properties(absl_strerror_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;608;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_strerror_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_strerror_test.exe")
  set_tests_properties(absl_strerror_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;608;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_strerror_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_fast_type_id_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_fast_type_id_test.exe")
  set_tests_properties(absl_fast_type_id_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;636;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_fast_type_id_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_fast_type_id_test.exe")
  set_tests_properties(absl_fast_type_id_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;636;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_fast_type_id_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_fast_type_id_test.exe")
  set_tests_properties(absl_fast_type_id_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;636;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_fast_type_id_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_fast_type_id_test.exe")
  set_tests_properties(absl_fast_type_id_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;636;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_fast_type_id_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_prefetch_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_prefetch_test.exe")
  set_tests_properties(absl_prefetch_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;663;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_prefetch_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_prefetch_test.exe")
  set_tests_properties(absl_prefetch_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;663;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_prefetch_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_prefetch_test.exe")
  set_tests_properties(absl_prefetch_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;663;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_prefetch_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_prefetch_test.exe")
  set_tests_properties(absl_prefetch_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;663;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_prefetch_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_optimization_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_optimization_test.exe")
  set_tests_properties(absl_optimization_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;676;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_optimization_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_optimization_test.exe")
  set_tests_properties(absl_optimization_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;676;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_optimization_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_optimization_test.exe")
  set_tests_properties(absl_optimization_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;676;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_optimization_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_optimization_test.exe")
  set_tests_properties(absl_optimization_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;676;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/base/CMakeLists.txt;0;")
else()
  add_test(absl_optimization_test NOT_AVAILABLE)
endif()
