# CMake generated Testfile for 
# Source directory: C:/git/library/abseil/abseil-cpp/absl/strings
# Build directory: C:/git/library/abseil/abseil-cpp/absl/strings
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_match_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_match_test.exe")
  set_tests_properties(absl_match_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;100;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_match_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_match_test.exe")
  set_tests_properties(absl_match_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;100;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_match_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_match_test.exe")
  set_tests_properties(absl_match_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;100;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_match_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_match_test.exe")
  set_tests_properties(absl_match_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;100;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_match_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_escaping_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_escaping_test.exe")
  set_tests_properties(absl_escaping_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;113;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_escaping_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_escaping_test.exe")
  set_tests_properties(absl_escaping_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;113;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_escaping_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_escaping_test.exe")
  set_tests_properties(absl_escaping_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;113;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_escaping_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_escaping_test.exe")
  set_tests_properties(absl_escaping_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;113;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_escaping_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_ascii_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_ascii_test.exe")
  set_tests_properties(absl_ascii_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;127;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_ascii_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_ascii_test.exe")
  set_tests_properties(absl_ascii_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;127;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_ascii_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_ascii_test.exe")
  set_tests_properties(absl_ascii_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;127;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_ascii_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_ascii_test.exe")
  set_tests_properties(absl_ascii_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;127;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_ascii_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_damerau_levenshtein_distance_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_damerau_levenshtein_distance_test.exe")
  set_tests_properties(absl_damerau_levenshtein_distance_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;140;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_damerau_levenshtein_distance_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_damerau_levenshtein_distance_test.exe")
  set_tests_properties(absl_damerau_levenshtein_distance_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;140;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_damerau_levenshtein_distance_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_damerau_levenshtein_distance_test.exe")
  set_tests_properties(absl_damerau_levenshtein_distance_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;140;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_damerau_levenshtein_distance_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_damerau_levenshtein_distance_test.exe")
  set_tests_properties(absl_damerau_levenshtein_distance_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;140;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_damerau_levenshtein_distance_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_memutil_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_memutil_test.exe")
  set_tests_properties(absl_memutil_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;153;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_memutil_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_memutil_test.exe")
  set_tests_properties(absl_memutil_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;153;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_memutil_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_memutil_test.exe")
  set_tests_properties(absl_memutil_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;153;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_memutil_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_memutil_test.exe")
  set_tests_properties(absl_memutil_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;153;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_memutil_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_utf8_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_utf8_test.exe")
  set_tests_properties(absl_utf8_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;167;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_utf8_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_utf8_test.exe")
  set_tests_properties(absl_utf8_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;167;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_utf8_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_utf8_test.exe")
  set_tests_properties(absl_utf8_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;167;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_utf8_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_utf8_test.exe")
  set_tests_properties(absl_utf8_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;167;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_utf8_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_string_constant_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_string_constant_test.exe")
  set_tests_properties(absl_string_constant_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;181;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_string_constant_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_string_constant_test.exe")
  set_tests_properties(absl_string_constant_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;181;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_string_constant_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_string_constant_test.exe")
  set_tests_properties(absl_string_constant_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;181;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_string_constant_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_string_constant_test.exe")
  set_tests_properties(absl_string_constant_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;181;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_string_constant_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_string_view_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_string_view_test.exe")
  set_tests_properties(absl_string_view_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;194;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_string_view_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_string_view_test.exe")
  set_tests_properties(absl_string_view_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;194;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_string_view_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_string_view_test.exe")
  set_tests_properties(absl_string_view_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;194;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_string_view_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_string_view_test.exe")
  set_tests_properties(absl_string_view_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;194;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_string_view_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_substitute_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_substitute_test.exe")
  set_tests_properties(absl_substitute_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;209;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_substitute_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_substitute_test.exe")
  set_tests_properties(absl_substitute_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;209;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_substitute_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_substitute_test.exe")
  set_tests_properties(absl_substitute_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;209;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_substitute_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_substitute_test.exe")
  set_tests_properties(absl_substitute_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;209;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_substitute_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_str_replace_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_str_replace_test.exe")
  set_tests_properties(absl_str_replace_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;222;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_str_replace_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_str_replace_test.exe")
  set_tests_properties(absl_str_replace_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;222;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_str_replace_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_str_replace_test.exe")
  set_tests_properties(absl_str_replace_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;222;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_str_replace_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_str_replace_test.exe")
  set_tests_properties(absl_str_replace_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;222;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_str_replace_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_str_split_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_str_split_test.exe")
  set_tests_properties(absl_str_split_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;234;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_str_split_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_str_split_test.exe")
  set_tests_properties(absl_str_split_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;234;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_str_split_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_str_split_test.exe")
  set_tests_properties(absl_str_split_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;234;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_str_split_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_str_split_test.exe")
  set_tests_properties(absl_str_split_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;234;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_str_split_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_ostringstream_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_ostringstream_test.exe")
  set_tests_properties(absl_ostringstream_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;251;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_ostringstream_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_ostringstream_test.exe")
  set_tests_properties(absl_ostringstream_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;251;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_ostringstream_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_ostringstream_test.exe")
  set_tests_properties(absl_ostringstream_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;251;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_ostringstream_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_ostringstream_test.exe")
  set_tests_properties(absl_ostringstream_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;251;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_ostringstream_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_resize_uninitialized_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_resize_uninitialized_test.exe")
  set_tests_properties(absl_resize_uninitialized_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;263;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_resize_uninitialized_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_resize_uninitialized_test.exe")
  set_tests_properties(absl_resize_uninitialized_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;263;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_resize_uninitialized_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_resize_uninitialized_test.exe")
  set_tests_properties(absl_resize_uninitialized_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;263;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_resize_uninitialized_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_resize_uninitialized_test.exe")
  set_tests_properties(absl_resize_uninitialized_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;263;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_resize_uninitialized_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_str_join_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_str_join_test.exe")
  set_tests_properties(absl_str_join_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;278;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_str_join_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_str_join_test.exe")
  set_tests_properties(absl_str_join_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;278;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_str_join_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_str_join_test.exe")
  set_tests_properties(absl_str_join_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;278;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_str_join_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_str_join_test.exe")
  set_tests_properties(absl_str_join_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;278;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_str_join_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_str_cat_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_str_cat_test.exe")
  set_tests_properties(absl_str_cat_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;293;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_str_cat_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_str_cat_test.exe")
  set_tests_properties(absl_str_cat_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;293;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_str_cat_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_str_cat_test.exe")
  set_tests_properties(absl_str_cat_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;293;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_str_cat_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_str_cat_test.exe")
  set_tests_properties(absl_str_cat_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;293;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_str_cat_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_numbers_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_numbers_test.exe")
  set_tests_properties(absl_numbers_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;307;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_numbers_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_numbers_test.exe")
  set_tests_properties(absl_numbers_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;307;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_numbers_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_numbers_test.exe")
  set_tests_properties(absl_numbers_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;307;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_numbers_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_numbers_test.exe")
  set_tests_properties(absl_numbers_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;307;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_numbers_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_strip_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_strip_test.exe")
  set_tests_properties(absl_strip_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;327;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_strip_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_strip_test.exe")
  set_tests_properties(absl_strip_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;327;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_strip_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_strip_test.exe")
  set_tests_properties(absl_strip_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;327;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_strip_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_strip_test.exe")
  set_tests_properties(absl_strip_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;327;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_strip_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_char_map_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_char_map_test.exe")
  set_tests_properties(absl_char_map_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;340;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_char_map_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_char_map_test.exe")
  set_tests_properties(absl_char_map_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;340;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_char_map_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_char_map_test.exe")
  set_tests_properties(absl_char_map_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;340;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_char_map_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_char_map_test.exe")
  set_tests_properties(absl_char_map_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;340;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_char_map_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_charconv_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_charconv_test.exe")
  set_tests_properties(absl_charconv_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;352;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_charconv_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_charconv_test.exe")
  set_tests_properties(absl_charconv_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;352;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_charconv_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_charconv_test.exe")
  set_tests_properties(absl_charconv_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;352;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_charconv_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_charconv_test.exe")
  set_tests_properties(absl_charconv_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;352;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_charconv_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_charconv_parse_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_charconv_parse_test.exe")
  set_tests_properties(absl_charconv_parse_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;366;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_charconv_parse_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_charconv_parse_test.exe")
  set_tests_properties(absl_charconv_parse_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;366;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_charconv_parse_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_charconv_parse_test.exe")
  set_tests_properties(absl_charconv_parse_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;366;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_charconv_parse_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_charconv_parse_test.exe")
  set_tests_properties(absl_charconv_parse_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;366;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_charconv_parse_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_charconv_bigint_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_charconv_bigint_test.exe")
  set_tests_properties(absl_charconv_bigint_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;381;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_charconv_bigint_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_charconv_bigint_test.exe")
  set_tests_properties(absl_charconv_bigint_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;381;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_charconv_bigint_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_charconv_bigint_test.exe")
  set_tests_properties(absl_charconv_bigint_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;381;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_charconv_bigint_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_charconv_bigint_test.exe")
  set_tests_properties(absl_charconv_bigint_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;381;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_charconv_bigint_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_str_format_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_str_format_test.exe")
  set_tests_properties(absl_str_format_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;442;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_str_format_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_str_format_test.exe")
  set_tests_properties(absl_str_format_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;442;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_str_format_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_str_format_test.exe")
  set_tests_properties(absl_str_format_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;442;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_str_format_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_str_format_test.exe")
  set_tests_properties(absl_str_format_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;442;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_str_format_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_str_format_extension_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_str_format_extension_test.exe")
  set_tests_properties(absl_str_format_extension_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;457;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_str_format_extension_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_str_format_extension_test.exe")
  set_tests_properties(absl_str_format_extension_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;457;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_str_format_extension_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_str_format_extension_test.exe")
  set_tests_properties(absl_str_format_extension_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;457;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_str_format_extension_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_str_format_extension_test.exe")
  set_tests_properties(absl_str_format_extension_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;457;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_str_format_extension_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_str_format_arg_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_str_format_arg_test.exe")
  set_tests_properties(absl_str_format_arg_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;471;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_str_format_arg_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_str_format_arg_test.exe")
  set_tests_properties(absl_str_format_arg_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;471;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_str_format_arg_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_str_format_arg_test.exe")
  set_tests_properties(absl_str_format_arg_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;471;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_str_format_arg_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_str_format_arg_test.exe")
  set_tests_properties(absl_str_format_arg_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;471;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_str_format_arg_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_str_format_bind_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_str_format_bind_test.exe")
  set_tests_properties(absl_str_format_bind_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;484;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_str_format_bind_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_str_format_bind_test.exe")
  set_tests_properties(absl_str_format_bind_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;484;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_str_format_bind_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_str_format_bind_test.exe")
  set_tests_properties(absl_str_format_bind_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;484;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_str_format_bind_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_str_format_bind_test.exe")
  set_tests_properties(absl_str_format_bind_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;484;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_str_format_bind_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_str_format_checker_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_str_format_checker_test.exe")
  set_tests_properties(absl_str_format_checker_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;496;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_str_format_checker_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_str_format_checker_test.exe")
  set_tests_properties(absl_str_format_checker_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;496;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_str_format_checker_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_str_format_checker_test.exe")
  set_tests_properties(absl_str_format_checker_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;496;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_str_format_checker_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_str_format_checker_test.exe")
  set_tests_properties(absl_str_format_checker_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;496;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_str_format_checker_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_str_format_convert_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_str_format_convert_test.exe")
  set_tests_properties(absl_str_format_convert_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;508;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_str_format_convert_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_str_format_convert_test.exe")
  set_tests_properties(absl_str_format_convert_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;508;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_str_format_convert_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_str_format_convert_test.exe")
  set_tests_properties(absl_str_format_convert_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;508;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_str_format_convert_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_str_format_convert_test.exe")
  set_tests_properties(absl_str_format_convert_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;508;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_str_format_convert_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_str_format_output_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_str_format_output_test.exe")
  set_tests_properties(absl_str_format_output_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;524;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_str_format_output_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_str_format_output_test.exe")
  set_tests_properties(absl_str_format_output_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;524;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_str_format_output_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_str_format_output_test.exe")
  set_tests_properties(absl_str_format_output_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;524;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_str_format_output_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_str_format_output_test.exe")
  set_tests_properties(absl_str_format_output_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;524;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_str_format_output_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_str_format_parser_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_str_format_parser_test.exe")
  set_tests_properties(absl_str_format_parser_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;537;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_str_format_parser_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_str_format_parser_test.exe")
  set_tests_properties(absl_str_format_parser_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;537;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_str_format_parser_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_str_format_parser_test.exe")
  set_tests_properties(absl_str_format_parser_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;537;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_str_format_parser_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_str_format_parser_test.exe")
  set_tests_properties(absl_str_format_parser_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;537;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_str_format_parser_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_pow10_helper_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_pow10_helper_test.exe")
  set_tests_properties(absl_pow10_helper_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;565;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_pow10_helper_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_pow10_helper_test.exe")
  set_tests_properties(absl_pow10_helper_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;565;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_pow10_helper_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_pow10_helper_test.exe")
  set_tests_properties(absl_pow10_helper_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;565;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_pow10_helper_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_pow10_helper_test.exe")
  set_tests_properties(absl_pow10_helper_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;565;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_pow10_helper_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_cordz_update_tracker_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_cordz_update_tracker_test.exe")
  set_tests_properties(absl_cordz_update_tracker_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;631;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_cordz_update_tracker_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_cordz_update_tracker_test.exe")
  set_tests_properties(absl_cordz_update_tracker_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;631;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_cordz_update_tracker_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_cordz_update_tracker_test.exe")
  set_tests_properties(absl_cordz_update_tracker_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;631;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_cordz_update_tracker_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_cordz_update_tracker_test.exe")
  set_tests_properties(absl_cordz_update_tracker_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;631;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_cordz_update_tracker_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_cordz_functions_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_cordz_functions_test.exe")
  set_tests_properties(absl_cordz_functions_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;663;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_cordz_functions_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_cordz_functions_test.exe")
  set_tests_properties(absl_cordz_functions_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;663;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_cordz_functions_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_cordz_functions_test.exe")
  set_tests_properties(absl_cordz_functions_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;663;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_cordz_functions_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_cordz_functions_test.exe")
  set_tests_properties(absl_cordz_functions_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;663;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_cordz_functions_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_cordz_handle_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_cordz_handle_test.exe")
  set_tests_properties(absl_cordz_handle_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;707;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_cordz_handle_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_cordz_handle_test.exe")
  set_tests_properties(absl_cordz_handle_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;707;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_cordz_handle_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_cordz_handle_test.exe")
  set_tests_properties(absl_cordz_handle_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;707;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_cordz_handle_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_cordz_handle_test.exe")
  set_tests_properties(absl_cordz_handle_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;707;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_cordz_handle_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_cordz_info_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_cordz_info_test.exe")
  set_tests_properties(absl_cordz_info_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;751;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_cordz_info_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_cordz_info_test.exe")
  set_tests_properties(absl_cordz_info_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;751;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_cordz_info_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_cordz_info_test.exe")
  set_tests_properties(absl_cordz_info_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;751;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_cordz_info_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_cordz_info_test.exe")
  set_tests_properties(absl_cordz_info_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;751;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_cordz_info_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_cordz_info_statistics_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_cordz_info_statistics_test.exe")
  set_tests_properties(absl_cordz_info_statistics_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;773;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_cordz_info_statistics_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_cordz_info_statistics_test.exe")
  set_tests_properties(absl_cordz_info_statistics_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;773;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_cordz_info_statistics_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_cordz_info_statistics_test.exe")
  set_tests_properties(absl_cordz_info_statistics_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;773;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_cordz_info_statistics_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_cordz_info_statistics_test.exe")
  set_tests_properties(absl_cordz_info_statistics_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;773;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_cordz_info_statistics_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_cordz_sample_token_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_cordz_sample_token_test.exe")
  set_tests_properties(absl_cordz_sample_token_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;810;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_cordz_sample_token_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_cordz_sample_token_test.exe")
  set_tests_properties(absl_cordz_sample_token_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;810;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_cordz_sample_token_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_cordz_sample_token_test.exe")
  set_tests_properties(absl_cordz_sample_token_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;810;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_cordz_sample_token_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_cordz_sample_token_test.exe")
  set_tests_properties(absl_cordz_sample_token_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;810;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_cordz_sample_token_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_cordz_update_scope_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_cordz_update_scope_test.exe")
  set_tests_properties(absl_cordz_update_scope_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;849;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_cordz_update_scope_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_cordz_update_scope_test.exe")
  set_tests_properties(absl_cordz_update_scope_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;849;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_cordz_update_scope_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_cordz_update_scope_test.exe")
  set_tests_properties(absl_cordz_update_scope_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;849;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_cordz_update_scope_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_cordz_update_scope_test.exe")
  set_tests_properties(absl_cordz_update_scope_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;849;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_cordz_update_scope_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_cord_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_cord_test.exe")
  set_tests_properties(absl_cord_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;955;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_cord_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_cord_test.exe")
  set_tests_properties(absl_cord_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;955;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_cord_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_cord_test.exe")
  set_tests_properties(absl_cord_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;955;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_cord_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_cord_test.exe")
  set_tests_properties(absl_cord_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;955;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_cord_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_cord_data_edge_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_cord_data_edge_test.exe")
  set_tests_properties(absl_cord_data_edge_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;979;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_cord_data_edge_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_cord_data_edge_test.exe")
  set_tests_properties(absl_cord_data_edge_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;979;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_cord_data_edge_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_cord_data_edge_test.exe")
  set_tests_properties(absl_cord_data_edge_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;979;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_cord_data_edge_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_cord_data_edge_test.exe")
  set_tests_properties(absl_cord_data_edge_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;979;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_cord_data_edge_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_cord_rep_btree_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_cord_rep_btree_test.exe")
  set_tests_properties(absl_cord_rep_btree_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;996;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_cord_rep_btree_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_cord_rep_btree_test.exe")
  set_tests_properties(absl_cord_rep_btree_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;996;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_cord_rep_btree_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_cord_rep_btree_test.exe")
  set_tests_properties(absl_cord_rep_btree_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;996;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_cord_rep_btree_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_cord_rep_btree_test.exe")
  set_tests_properties(absl_cord_rep_btree_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;996;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_cord_rep_btree_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_cord_rep_btree_navigator_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_cord_rep_btree_navigator_test.exe")
  set_tests_properties(absl_cord_rep_btree_navigator_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1015;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_cord_rep_btree_navigator_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_cord_rep_btree_navigator_test.exe")
  set_tests_properties(absl_cord_rep_btree_navigator_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1015;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_cord_rep_btree_navigator_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_cord_rep_btree_navigator_test.exe")
  set_tests_properties(absl_cord_rep_btree_navigator_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1015;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_cord_rep_btree_navigator_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_cord_rep_btree_navigator_test.exe")
  set_tests_properties(absl_cord_rep_btree_navigator_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1015;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_cord_rep_btree_navigator_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_cord_rep_btree_reader_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_cord_rep_btree_reader_test.exe")
  set_tests_properties(absl_cord_rep_btree_reader_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1033;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_cord_rep_btree_reader_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_cord_rep_btree_reader_test.exe")
  set_tests_properties(absl_cord_rep_btree_reader_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1033;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_cord_rep_btree_reader_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_cord_rep_btree_reader_test.exe")
  set_tests_properties(absl_cord_rep_btree_reader_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1033;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_cord_rep_btree_reader_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_cord_rep_btree_reader_test.exe")
  set_tests_properties(absl_cord_rep_btree_reader_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1033;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_cord_rep_btree_reader_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_cord_rep_crc_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_cord_rep_crc_test.exe")
  set_tests_properties(absl_cord_rep_crc_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1051;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_cord_rep_crc_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_cord_rep_crc_test.exe")
  set_tests_properties(absl_cord_rep_crc_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1051;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_cord_rep_crc_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_cord_rep_crc_test.exe")
  set_tests_properties(absl_cord_rep_crc_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1051;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_cord_rep_crc_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_cord_rep_crc_test.exe")
  set_tests_properties(absl_cord_rep_crc_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1051;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_cord_rep_crc_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_cord_ring_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_cord_ring_test.exe")
  set_tests_properties(absl_cord_ring_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1066;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_cord_ring_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_cord_ring_test.exe")
  set_tests_properties(absl_cord_ring_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1066;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_cord_ring_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_cord_ring_test.exe")
  set_tests_properties(absl_cord_ring_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1066;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_cord_ring_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_cord_ring_test.exe")
  set_tests_properties(absl_cord_ring_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1066;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_cord_ring_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_cord_ring_reader_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_cord_ring_reader_test.exe")
  set_tests_properties(absl_cord_ring_reader_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1083;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_cord_ring_reader_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_cord_ring_reader_test.exe")
  set_tests_properties(absl_cord_ring_reader_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1083;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_cord_ring_reader_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_cord_ring_reader_test.exe")
  set_tests_properties(absl_cord_ring_reader_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1083;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_cord_ring_reader_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_cord_ring_reader_test.exe")
  set_tests_properties(absl_cord_ring_reader_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1083;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_cord_ring_reader_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_cordz_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_cordz_test.exe")
  set_tests_properties(absl_cordz_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1098;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_cordz_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_cordz_test.exe")
  set_tests_properties(absl_cordz_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1098;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_cordz_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_cordz_test.exe")
  set_tests_properties(absl_cordz_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1098;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_cordz_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_cordz_test.exe")
  set_tests_properties(absl_cordz_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;1098;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/strings/CMakeLists.txt;0;")
else()
  add_test(absl_cordz_test NOT_AVAILABLE)
endif()
