# CMake generated Testfile for 
# Source directory: C:/git/library/abseil/abseil-cpp/absl/profiling
# Build directory: C:/git/library/abseil/abseil-cpp/absl/profiling
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_sample_recorder_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_sample_recorder_test.exe")
  set_tests_properties(absl_sample_recorder_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;27;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_sample_recorder_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_sample_recorder_test.exe")
  set_tests_properties(absl_sample_recorder_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;27;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_sample_recorder_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_sample_recorder_test.exe")
  set_tests_properties(absl_sample_recorder_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;27;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_sample_recorder_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_sample_recorder_test.exe")
  set_tests_properties(absl_sample_recorder_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;27;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;0;")
else()
  add_test(absl_sample_recorder_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_exponential_biased_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_exponential_biased_test.exe")
  set_tests_properties(absl_exponential_biased_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;54;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_exponential_biased_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_exponential_biased_test.exe")
  set_tests_properties(absl_exponential_biased_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;54;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_exponential_biased_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_exponential_biased_test.exe")
  set_tests_properties(absl_exponential_biased_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;54;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_exponential_biased_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_exponential_biased_test.exe")
  set_tests_properties(absl_exponential_biased_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;54;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;0;")
else()
  add_test(absl_exponential_biased_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(absl_periodic_sampler_test "C:/git/library/abseil/abseil-cpp/bin/Debug/absl_periodic_sampler_test.exe")
  set_tests_properties(absl_periodic_sampler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;81;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(absl_periodic_sampler_test "C:/git/library/abseil/abseil-cpp/bin/Release/absl_periodic_sampler_test.exe")
  set_tests_properties(absl_periodic_sampler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;81;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(absl_periodic_sampler_test "C:/git/library/abseil/abseil-cpp/bin/MinSizeRel/absl_periodic_sampler_test.exe")
  set_tests_properties(absl_periodic_sampler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;81;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(absl_periodic_sampler_test "C:/git/library/abseil/abseil-cpp/bin/RelWithDebInfo/absl_periodic_sampler_test.exe")
  set_tests_properties(absl_periodic_sampler_test PROPERTIES  _BACKTRACE_TRIPLES "C:/git/library/abseil/abseil-cpp/CMake/AbseilHelpers.cmake;440;add_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;81;absl_cc_test;C:/git/library/abseil/abseil-cpp/absl/profiling/CMakeLists.txt;0;")
else()
  add_test(absl_periodic_sampler_test NOT_AVAILABLE)
endif()
